### ISSUE TITLE
list-remote returns nothing on macOS 10.12.6

### ISSUE THREAD

**Issue by stephenchu** [iamhsa/pkenv#1]
System:
```
  macOS 10.12.6
  curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
  pkenv 0.2.3
```

When I run `pkenv list-remote`, it returns nothing (exit status: 0). Upon further inspection, it looks like it is the presence of the`curl` option `--tlsv1.2` causing the curl to error out with "curl: (35) Unknown SSL protocol error in connection to releases.hashicorp.com:-9836" on my system. After taking out the `--tlsv1.2` option, the curl returns the html correctly.

Looking over at how tfenv does it thing, it appears that there is [this commit](https://github.com/kamatama41/tfenv/commit/affad484e65ec3f741f882d9122dea81488e3b8a) introduced recently that deals with this problem.

**Comment by stephenchu** [comment]
Additional information: It looks like the curl (listed above) that ships with my macOS, when using the `--tlsv1.2` option, it still uses tls 1.0 under Wireshark and thus rejected by the server.

Now that I have `brew install curl`, this new version of curl no longer return nothing:

```
› /usr/local/opt/curl/bin/curl --version
curl 7.55.1 (x86_64-apple-darwin16.7.0) libcurl/7.55.1 SecureTransport zlib/1.2.8
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
```

**Comment by iamhsa** [comment]
Sorry for the delay. I was in vacation, and completely disconnected. 
I try to fix this as soon as possible 
Thanks for opening this issue.

**Comment by stephenchu** [comment]
Yep! I tested it (both using the problematic `curl` and my brew installed `curl`). They all work.

🥇

**Comment by iamhsa** [comment]
Cool ! 
Thank for the test.
I merge it in master soon.
