### ISSUE TITLE
PKENV_REMOTE

### ISSUE THREAD

**Issue by gevans-web46** [iamhsa/pkenv#10]
Similar how to TFEnv works with TFENV_REMOTE, you can override the target URL for the Packer packages.

> String (Default: https://releases.hashicorp.com)
>To install from a remote other than the default
>$ TFENV_REMOTE=https://example.jfrog.io/artifactory/hashicorp

PR created - https://github.com/iamhsa/pkenv/pull/11

**Comment by iamhsa** [comment]
#11 merged !
Thanks !
