### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by kwilczynski** [iamhsa/pkenv#2]
Hi there @iamhsa! Thank you for working on this, it's very nice and I use it a lot.

I was wondering, whether you would be keen to officially cut a release? I have a Homebrew formula[1] that I use, and I wanted to submit it upstream so that others can benefit too. This would be far easier if we get a nice new release cut with all the fixes and updates you've added recently.

What do you think?

1. https://gist.github.com/kwilczynski/d49ffe816d372f2693e9aeae39e615bd

**Comment by iamhsa** [comment]
Hi,
I am happy  pkenv help you, thank you.
I think your demand is a good idea, I do it as soon as possible.

Some notes : 
- I don't use Mac and Hombrew so I could not help you a lot.
- I look your gist and I think your file is wrongly named (tfenv.rb -> pkenv.rb).
- Could you make a pull request with README.md modified with Hombrew installation ?

I will post a new comment when I cut a release.
Thanks again for using pkenv and the issue.

**Comment by kwilczynski** [comment]
@iamhsa thank you!

Indeed, I had tfenv there, and I correct it there. Don't worry about OS X support, I will handle that - 
plus it works great at the moment for me (see below).

<img width="859" alt="screen shot 2017-11-16 at 10 47 58" src="https://user-images.githubusercontent.com/250723/32884749-ace137de-cabb-11e7-9dab-bc88782edd9d.png">

**Comment by iamhsa** [comment]
Thank you.
Could you check https://github.com/iamhsa/pkenv/releases ?
Now I have 0.3.0.

Please let me now if it's ok for you.

**Comment by kwilczynski** [comment]
@iamhsa looks great and works great. 👌 

I've opened a Pull Request against Homebrew core, but it was rejected due to pkenv not being known well enough yet (give it some time, though).

Meanwhile, I have created a Homebrew tap to host pkenv formulate for Homebrew. You can find it at https://github.com/kwilczynski/homebrew-pkenv.

Let me know if you would prefer to host a Homebrew tap yourself - in which case I am going to transfer ownership of the repository to you.

**Comment by kwilczynski** [comment]
The link to the Homebrew core Pull Request for posterity: https://github.com/Homebrew/homebrew-core/pull/20712

**Comment by iamhsa** [comment]
> Let me know if you would prefer to host a Homebrew tap yourself 
If it's ok for you, you can stay owner.

> pkenv not being known well enough yet
Sure :-) And I don't communicate a lot on pkenv
As I know It's mainly useful for me and some of my colleagues

If it's ok for you can I close this issue ?

**Comment by kwilczynski** [comment]
@iamhsa sure thing! Go ahead! Thank you for all the help!
