### ISSUE TITLE
Version inconsistency 0.5.0 / 0.5.2

### ISSUE THREAD

**Issue by schneidexe** [iamhsa/pkenv#9]
When I download 0.5.0 and run `pkenv --version` it prints `0.5.2`. Not a big deal but rather inconsistent so I just wanted to raise awareness in case your plan new releases.
```

$ curl -sL https://github.com/iamhsa/pkenv/archive/0.5.0.tar.gz | tar xzf -
$ ./pkenv-0.5.0/bin/pkenv --version
pkenv 0.5.2
```

**Comment by iamhsa** [comment]
Arfff ! My bad !
Thanks for catching that ! 

I think I'll generate a 0.5.2 release to fix that.

**Comment by iamhsa** [comment]
[Release 0.5.2](https://github.com/iamhsa/pkenv/releases/tag/0.5.2) to address this issue.
